### ISSUE TITLE
建议添加订阅节点过滤功能

### ISSUE THREAD

**Issue by Ansen** [tindy2013/stairspeedtest-reborn#113]
有时候订阅节点太多，一些低等级节点测速没什么意义，建议添加通过名称过滤节点

类似下图这样
![图片](https://user-images.githubusercontent.com/676412/102586682-8f709100-4145-11eb-80a4-08c437e0f406.png)

**Comment by phlinhng** [comment]
支持這個提議

**Comment by jdjaljf** [comment]
楼主这个截图，是什么软件？

**Comment by Ansen** [comment]
> 楼主这个截图，是什么软件？

OpenWrt R20.9.15 / LuCI Master (git-20.256.12360-1a54222)

**Comment by mrxtryagin** [comment]
配置文件里面有:

[common]
;Excluded remarks, nodes with these remarks will be ignored, supports regular expression
;one remark per line, index starts at 0
exclude_remarks0=(剩余流量|到期时间|过期时间|官网地址|产品名称)

;Included remarks, if defined (";" removed), only nodes with these remarks will be tested, supports regular expression
;one remark per line, index starts at 0
;include_remarks0=香港

可以善用include

**Comment by Ansen** [comment]
> 
> 
> 配置文件里面有:
> 
> [common]
> ;Excluded remarks, nodes with these remarks will be ignored, supports regular expression
> ;one remark per line, index starts at 0
> exclude_remarks0=(剩余流量|到期时间|过期时间|官网地址|产品名称)
> 
> ;Included remarks, if defined (";" removed), only nodes with these remarks will be tested, supports regular expression
> ;one remark per line, index starts at 0
> ;include_remarks0=香港
> 
> 可以善用include

谢谢

不好意思，我没有注意到有配置文件。
