### ISSUE TITLE
无关网址跳转是有意还是无意？

### ISSUE THREAD

**Issue by FoliageOwO** [tindy2013/stairspeedtest-reborn#182]
如题，在打开 `webserver.bat` 时会跳转到 `ww6.web1.ospf.in` 这个网址。

这个网址和此项目没有任何关系吧？一个本地的项目为什么要跳转到此网站？（目前该域名正在被出售）

我的猜测是，跳转 `ospf.in` 可能是作者的个人网站，或其他什么网站的引流或广告？

希望开发者可以回应一下疑惑。

![image](https://github.com/tindy2013/stairspeedtest-reborn/assets/58383985/254e9601-96c7-4227-880f-96a1de70cac1)

**Comment by tindy2013** [comment]
https://web.archive.org/web/20200912124623/https://web1.ospf.in/
Commit https://github.com/tindy2013/stairspeedtest-reborn/commit/8b24939a10defcd86a0dcd1f1b5c4066a0e4aa1d

**Comment by FoliageOwO** [comment]
> [web.archive.org/web/20200912124623/https://web1.ospf.in](https://web.archive.org/web/20200912124623/https://web1.ospf.in/) Commit [8b24939](https://github.com/tindy2013/stairspeedtest-reborn/commit/8b24939a10defcd86a0dcd1f1b5c4066a0e4aa1d)

明白了，谢谢。:)
