### ISSUE TITLE
Speedtest测速时出现问题

### ISSUE THREAD

**Issue by Kawaii-KM** [tindy2013/stairspeedtest-reborn#22]
系统 macOS High Sierra
MacBook Air (13-inch, Mid 2011)

[错误代码](https://telegra.ph/Speedtest%E6%B5%8B%E9%80%9F%E6%97%B6%E5%87%BA%E7%8E%B0%E9%97%AE%E9%A2%98-11-10)

**Comment by tindy2013** [comment]
@Kawaii-KM 已知是直接双击打开程序导致当前工作目录非程序目录所致 将于晚些时候修复此问题

**Comment by tindy2013** [comment]
@tindy2013 在此之前你可以在终端中手动切换目录到程序目录再运行程序来解决
