### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by Fight** [tindy2013/stairspeedtest-reborn#24]
2 warnings generated.
  CCLD     ss-local
2 warnings generated.
  CCLD     libshadowsocks-libev.la
ld: warning: directory not found for option '-L/usr/local/opt/ruby/lib'
make[2]: Nothing to be done for `all-am'.
installing v2ray from brew
==> Installing v2ray-core from v2ray/v2ray
==> Downloading https://github.com/v2ray/v2ray-core/releases/download/v4.21.3/v2ray-macos.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/41912791/57563e00-f9d9-11e9-91ca-6263c0465e11?X-Amz-
######################################################################## 100.0%
==> Caveats
To have launchd start v2ray/v2ray/v2ray-core now and restart at login:
  brew services start v2ray/v2ray/v2ray-core
Or, if you don't want/need a background service you can just run:
  v2ray -config=/usr/local/etc/v2ray/config.json
==> Summary
🍺  /usr/local/Cellar/v2ray-core/4.21.3: 7 files, 34MB, built in 53 seconds
all done!
➜  stairspeedtest-reborn git:(master) ✗ sh ./build.macos.sh  
Undefined symbols for architecture x86_64:
  "ssrspeed_webserver_routine(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int)", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
➜  stairspeedtest-reborn git:(master) ✗ 
➜  stairspeedtest-reborn git:(master) ✗ 
➜  stairspeedtest-reborn git:(master) ✗ 
➜  stairspeedtest-reborn git:(master) ✗ 
➜  stairspeedtest-reborn git:(master) ✗ sh ./build.macos.sh  
mkdir: obj: File exists
mkdir: bin: File exists
Undefined symbols for architecture x86_64:
  "ssrspeed_webserver_routine(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int)", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Fight** [comment]
Mac os: 10.14.6 (18G87)
(Xcode 11.2.1)

**Comment by tindy2013** [comment]
Fixed on commit [82f3fbc9ab5b7e011cc0e1fcce79da3ae0caeaf1](https://github.com/tindy2013/stairspeedtest-reborn/commit/82f3fbc9ab5b7e011cc0e1fcce79da3ae0caeaf1)
