### ISSUE TITLE
build on macos  fail on dev

### ISSUE THREAD

**Issue by Fight** [tindy2013/stairspeedtest-reborn#25]
+ c++ -o stairspeedtest obj/geoip.o obj/logger.o obj/main.o obj/misc.o obj/multithread_test.o obj/printout.o obj/processes.o obj/rapidjson_extra.o obj/renderer.o obj/rulematch.o obj/socket.o obj/speedtestutil.o obj/tcping.o obj/webget.o obj/webgui_wrapper.o obj/webserver_libevent.o -L/usr/local/opt/openssl@1.1/lib -lcurl -lPNGwriter -lpng -lfreetype -lz -lssl -lcrypto -lyaml-cpp -ldl -lpthread
Undefined symbols for architecture x86_64:
  "_evbuffer_add", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evbuffer_get_length", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evbuffer_pullup", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_event_base_dispatch", referenced from:
      httpserver_dispatch(void*) in webserver_libevent.o
  "_event_dispatch", referenced from:
      start_web_server(void*) in webserver_libevent.o
  "_event_init", referenced from:
      start_web_server(void*) in webserver_libevent.o
      start_web_server_multi(void*) in webserver_libevent.o
  "_evhttp_accept_socket", referenced from:
      start_web_server_multi(void*) in webserver_libevent.o
  "_evhttp_add_header", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evhttp_find_header", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evhttp_free", referenced from:
      start_web_server(void*) in webserver_libevent.o
  "_evhttp_new", referenced from:
      start_web_server_multi(void*) in webserver_libevent.o
  "_evhttp_request_get_output_buffer", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evhttp_request_get_uri", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evhttp_send_error", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evhttp_send_reply", referenced from:
      OnReq(evhttp_request*, void*) in webserver_libevent.o
  "_evhttp_set_allowed_methods", referenced from:
      start_web_server(void*) in webserver_libevent.o
      start_web_server_multi(void*) in webserver_libevent.o
  "_evhttp_set_gencb", referenced from:
      start_web_server(void*) in webserver_libevent.o
      start_web_server_multi(void*) in webserver_libevent.o
  "_evhttp_start", referenced from:
      start_web_server(void*) in webserver_libevent.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
➜  stairspeedtest-reborn git:(dev) ✗

**Comment by tindy2013** [comment]
Missing linking library added in commit [f9b0327e](https://github.com/tindy2013/stairspeedtest-reborn/commit/f9b0327e525f7a93cc4c51e23ca997ec474a4fa0)
