### ISSUE TITLE
输出图像中没有MaxSpeed项

### ISSUE THREAD

**Issue by jyuan15** [tindy2013/stairspeedtest-reborn#28]
Win7 32位。

已经在配置文件中把“导出maxspeed”和“多个测试链接输出为一个图像”都设置为true了，但仍然输出多个图像，并且图片中没有Maxspeed项。

**Comment by tindy2013** [comment]
@jyuan15 读取配置文件有些问题 请尝试使用其他版本

**Comment by jyuan15** [comment]
@tindy2013 嗯，试了下，0.3.0可以，望后续版本修复，谢谢

**Comment by jyuan15** [comment]
哎，0.3.0也有问题，不能 Ping Google，数据全部为0

**Comment by jyuan15** [comment]
找到原因了，不能用记事本编辑，用notepad编辑后就能正常读取pref了。

**Comment by tindy2013** [comment]
@jyuan15 实测记事本会添加BOM到文件开头处导致读取时出现问题 将会在未来的版本修复
