### ISSUE TITLE
测速结果可否加上本地带宽测速的结果或者更多信息？

### ISSUE THREAD

**Issue by adamw92** [tindy2013/stairspeedtest-reborn#33]
很多人分享测速图的时候并不会说明自己本次测速的网络环境，带宽如何，运营商信息等。
测速环境的情况还是挺重要的…

**Comment by PYniang** [comment]
@adamw92 咱建议直接生成，还测啥，自己填

**Comment by adamw92** [comment]
@PYniang 自己填一下信息然后简单测个速最后都生成到结果里，over。
无论怎么搞，最后结果里应该有相关信息比较好

**Comment by PYniang** [comment]
@adamw92 是不是还要把家庭地址填进去?

**Comment by adamw92** [comment]
> @adamw92 是不是还要把家庭地址填进去?

就加个类似中国电信，200M，本地测速：XXX
测速结果有这个信息不是更有价值么…

**Comment by PYniang** [comment]
@adamw92 请问如何知道恁家带宽?要不身份证啥的给我我去营业厅查?

**Comment by adamw92** [comment]
> @adamw92 请问如何知道恁家带宽?要不身份证啥的给我我去营业厅查?

前两项可以手工填写…甚至只有运营商名称都行，软件进行测速，最后加进去。

这样避免看到测速图的时候，不好判断到底是节点速度跑不上去还是测速环境只能跑这么多。

**Comment by PYniang** [comment]
@adamw92 那直接说明不好吗?为什么要来找软件 ，反正都是手动

**Comment by adamw92** [comment]
@PYniang 软件进行本地测速然后加到结果图里。放到一起不是更直观更方便么。

**Comment by PYniang** [comment]
@adamw92 @tindy2013 请将软件做成全自动的，自动猜测要测哪个机场，自动测速，自动显示所有个人信息，谢谢茄子

**Comment by tindy2013** [comment]
@adamw92 暂时没有添加的计划
