### ISSUE TITLE
Not supported chacha20-ietf-poly1305 method with tls obfs

### ISSUE THREAD

**Issue by axelburks** [tindy2013/stairspeedtest-reborn#34]
Not supported on macOS :
chacha20-ietf-poly1305, obfs=tls, obfs-host=windows.com
![image](https://user-images.githubusercontent.com/11376445/71257152-f100f280-236d-11ea-9175-46761edc3712.png)
 
![image](https://user-images.githubusercontent.com/11376445/71257177-fbbb8780-236d-11ea-9f1e-edaf8a4d4ba6.png)

**Comment by axelburks** [comment]
@tindy2013 请问有什么解决方法或者就是等更新就好了😢

**Comment by tindy2013** [comment]
应该是解析问题 方便的话提供下订阅地址来检查

**Comment by axelburks** [comment]
@tindy2013 如何私聊？Telegram？

**Comment by tindy2013** [comment]
@axelburks https://t.me/stairspeedtest 附属讨论组
