### ISSUE TITLE
你好 linux端 bug 怎么解决

### ISSUE THREAD

**Issue by lithromantic** [tindy2013/stairspeedtest-reborn#35]
你好 使用debian9  bash webgui.sh 之后，网页里面的上下行带宽直接无法测速N/A 

log 
ERROR  | process    | url:'http://103.56XXX.67:11145/' id:'1331787710586984416' remote:'117.XXX4' command:'./stairspeedtest' origin:'http://103.56XXX67:11145' pid:'17922' | Unexpected error while reading STDOUT from process: read |0: file already closed

**Comment by tindy2013** [comment]
@lithromantic 可以尝试使用 0.4.0 版本进行测试
