### ISSUE TITLE
部分节点不能测试

### ISSUE THREAD

**Issue by phoenixhu** [tindy2013/stairspeedtest-reborn#36]
部分节点无法测试
Loss 100%，Ping  AvgSpeed，MaxSpeed皆为0
但是节点实际情况是正常的，手动也可以ping通，windows，linux都试了，弄了一个晚上实在有点无解，SSRSpeed的也有这个问题

**Comment by tindy2013** [comment]
@phoenixhu 你不提供任何“部分节点”的信息的话我也帮不了你
