### ISSUE TITLE
订阅节点里有连续两个以上不通的节点就会卡住不动

### ISSUE THREAD

**Issue by BoyceLig** [tindy2013/stairspeedtest-reborn#45]
![image](https://user-images.githubusercontent.com/49801599/72705818-6511fe80-3b97-11ea-8242-f2a6791353ca.png)
![image](https://user-images.githubusercontent.com/49801599/72705886-8ffc5280-3b97-11ea-9913-c53aae4d3c9a.png)
![image](https://user-images.githubusercontent.com/49801599/72705942-adc9b780-3b97-11ea-9d0b-d9cd4df1b8a2.png)

**Comment by ltsj** [comment]
@BoyceLig 你回车试试看

**Comment by tindy2013** [comment]
Fixed on commit [7626789](https://github.com/tindy2013/stairspeedtest-reborn/commit/7626789fdbdce66ee760d9dbe745fa020396cf61)

**Comment by BoyceLig** [comment]
> @BoyceLig 你回车试试看

不管用

**Comment by BoyceLig** [comment]
> Fixed on commit [7626789](https://github.com/tindy2013/stairspeedtest-reborn/commit/7626789fdbdce66ee760d9dbe745fa020396cf61)
在哪里能用

**Comment by tindy2013** [comment]
@BoyceLig 即将发布 v0.6.1-beta

**Comment by BoyceLig** [comment]
> @BoyceLig 即将发布 v0.6.1-beta

好的
