### ISSUE TITLE
能否做成api方式？

### ISSUE THREAD

**Issue by wgleiz** [tindy2013/stairspeedtest-reborn#55]
您好，可否做成dll   是输入订阅地址或者ssr地址函数 输出详细信息的 api  二次开发使用， 由于不会c语言，希望提供dll版本

**Comment by tindy2013** [comment]
隔壁 https://github.com/tindy2013/subconverter （不过也不是 DLL😂）

**Comment by wgleiz** [comment]
我只是觉得里面的测试功能很实用，毕竟我还在体制内。&nbsp; &nbsp;奈何只会个易语言

我是想采集完后&nbsp;自动测速筛选掉不合格的&nbsp;组装成订阅地址存放于路由器




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tindy X"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上10:19
收件人: "tindy2013/stairspeedtest-reborn"<stairspeedtest-reborn@noreply.github.com&gt;; 
抄送: "Wgleiz"<wgleiz@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tindy2013/stairspeedtest-reborn] 能否做成api方式？ (#55)




隔壁 https://github.com/tindy2013/subconverter （不过也不是 DLL😂）

**Comment by tindy2013** [comment]
对于这个问题十分建议用 Clash 作为客户端 并使用 url-test 策略组选择速度最快的节点

**Comment by wgleiz** [comment]
我明天试试 但我还是期待您做成测速的dll 直接可以二次开发使用的发自我的华为手机-------- 原始邮件 --------发件人： Tindy X <notifications@github.com>日期： 2020年2月20日周四 22:46收件人： tindy2013/stairspeedtest-reborn <stairspeedtest-reborn@noreply.github.com>抄送： wgleiz <wgleiz@qq.com>, Author <author@noreply.github.com>主    题： Re: [tindy2013/stairspeedtest-reborn] 能否做成api方式？ (#55)对于这个问题十分建议用 Clash 作为客户端 并使用 url-test 策略组选择速度最快的节点
