### ISSUE TITLE
是否支持域名地址的测速

### ISSUE THREAD

**Issue by yjjcolin** [tindy2013/stairspeedtest-reborn#60]
我测试了Rixcloud的订阅地址，可以导入节点，但是我点Start开始测试，始终报错 invalid input。不知道是否是因为 Rixcloud的节点地址是域名而非IP地址导致的。所以想问一下是否支持域名形式的节点名称测速

**Comment by tindy2013** [comment]
@yjjcolin webserver 模式下请先选择模式和节点再开始测试
