### ISSUE TITLE
能不能增加把上次的测试设置和订阅地址保存的功能

### ISSUE THREAD

**Issue by hn2alice** [tindy2013/stairspeedtest-reborn#62]
感谢大神贡献出的这个好用的测速工具。
有个问题，就是，每次测速都要自己填写订阅地址和测速设置，如果能读取上次测速的配置，那么可以提升一些操作便捷性，更加简单好用。

**Comment by tindy2013** [comment]
可以用 `/u 订阅地址`  作为参数启动主程序来实现

**Comment by hn2alice** [comment]
> 可以用 `/u 订阅地址` 作为参数启动主程序来实现

测试了一下，单个订阅可以，多个订阅加   |    好像不行，控制台直接退出了，l类似这种，start stairspeedtest.exe /u  https://v2ray1|https:v2ray2，没成功
