### ISSUE TITLE
希望能使用youtube的速度进行判断，毕竟大多数需要网速的环境就是看youtube

### ISSUE THREAD

**Issue by Alex-coffen** [tindy2013/stairspeedtest-reborn#66]
希望能使用youtube的速度进行判断，毕竟大多数需要网速的环境就是看youtube

**Comment by mytml** [comment]
介于YouTube的视频缓存机制,并不能够说明节点的速度!所以没有测速的意义!

**Comment by Alex-coffen** [comment]
就是因为平时用你这个测了之后，使用测出来最好的server，结果youtube卡缓冲，用测速慢的反而没问题。
