### ISSUE TITLE
关于测速的建议

### ISSUE THREAD

**Issue by 643406834** [tindy2013/stairspeedtest-reborn#69]
测线路有个很重要的指标：丢包率。建议在里面添加多一个选项，测试ping 100个到谷歌的丢包率  url:http://www.gstatic.com/generate_204   多次测谷歌首页可能被封，用这个地址就不会，机场情况很复杂，用测试跑速度很快，但打开网页或者油管速度很慢，需要看多个数据，如ping值，带宽，丢包率

**Comment by wszydsp** [comment]
我也想要这个...!!!

**Comment by wkingnet** [comment]
ping only模式，不是有一列就是Lost吗？
