### ISSUE TITLE
可以加入Trojan节点的测速吗

### ISSUE THREAD

**Issue by ZPH666666** [tindy2013/stairspeedtest-reborn#71]
最近搭建了一个trojan节点，想要测试速度，请问大大能否在新版软件里加入Trojan的测速功能，感激不尽！

**Comment by tindy2013** [comment]
@ZPH666666 最近比较忙 未来会加入

**Comment by zack66** [comment]
@ZPH666666 你在用Trojan机场吗？

**Comment by pirately** [comment]
我也想问，能不能加入trojan

**Comment by tindy2013** [comment]
Added in commit [66c2c7b](https://github.com/tindy2013/stairspeedtest-reborn/commit/66c2c7b159b9ddffb45b2c662545921eb9bb63fd)
