### ISSUE TITLE
Web GUI中结果的速度排序无效

### ISSUE THREAD

**Issue by panngithub** [tindy2013/stairspeedtest-reborn#72]
环境：
v0.6.1-beta stairspeedtest_reborn_win64.7z
Windows 10 1909/Windows Server 2012 R2
Chrome 81.0.4044.92

运行webgui.bat进行测速后，Group/Remark/Loss/Ping均可通过点击进行排序，点击AvgSpeed/MaxSpeed后，右侧也会相应出现蓝色三角箭头，但下方数据仍然保持原样。

**Comment by tindy2013** [comment]
@panngithub 已知问题 未来会修复
