### ISSUE TITLE
ss 链接中含有复杂密码时，stairspeedtest 不能正确解析。

### ISSUE THREAD

**Issue by IceCodeNew** [tindy2013/stairspeedtest-reborn#74]
遇到问题的 ss 链接如下（我将所有的字母替换成了`A`，所有的数字替换成了`1`，没有改其他的字符或者调换位置）：
`ss://YWVzLTI1Ni1nY206fCp9QUFBJkFAQS4pJEFBL0FBMUFBQT9bQUFBQUFBQX1AMS4xLjEuMTo1NTU1NQ#备注`
密码部分单独拎出来如下：
`|*}AAA&A@A.)$AA/AA1AAA?[AAAAAAA}`

错误日志如下：
```
Current Server Group: SSProvider Remarks: 备注 Index: 1/1
Now performing TCP Ping...
Cannot resolve server address.
Now exporting picture...
Result picture saved to "results\20200430-180204.png".

Speed Test done. Press any key to exit...
```

我这段链接丢给官方的客户端是没有问题的。这块我已经尝试过很多次，筛掉了所有会导致 ss-server 不能正常运作的特殊字符。
希望 stairspeedtest 能改善对 ss 链接的解析。

**Comment by IceCodeNew** [comment]
不修就算了，咋直接关了呢？我分析问题加写 issue 也是很花时间的啊

**Comment by tindy2013** [comment]
@IceCodeNew 已经修复了

**Comment by IceCodeNew** [comment]
哦这样啊，是我误会了，不好意思，辛苦啦
谢谢
