### ISSUE TITLE
No valid link found. Please check your link.

### ISSUE THREAD

**Issue by w311ang** [tindy2013/stairspeedtest-reborn#75]
* Android 5.1.1
* Termux 0.73

订阅链接已作星号处理
```console
$ termux-chroot ./stairspeedtest                  Welcome to Stair Speedtest v0.6.1-beta!           Which stair do you want to test today? (Supports single Shadowsocks/ShadowsocksD/ShadowsocksR/V2Ray link and their subscribe links)
If you want to test more than one link, separate them with '|'.
Link: http://***
Found subscribe link.
If you have imported an V2Ray subscribe link which doesn't contain a Group Name, you can specify a custom name below.
If you have imported an Shadowsocks/ShadowsocksR link which contains a Group Name, press Enter to skip.
Custom Group Name:
Downloading subscription data...
Nothing returned from subscribe link. Please check your subscribe link.
No valid link found. Please check your link.

Speed Test done. Press any key to exit...
```
我抓包了下，发现Termux没有向订阅发出请求，而curl则正常，如下
![IMG_20200503_203646](https://user-images.githubusercontent.com/30381083/80914395-d5771100-8d7d-11ea-995d-25923a232409.jpg)
这个[issue](https://github.com/tindy2013/stairspeedtest-reborn/issues/54)问题貌似与我相似，但我并不想编译
希望可以直接提供订阅内容，而不作请求？

**Comment by walwan** [comment]
emmmmm，我建议重新编译stairspeedtest以及v2ray,v2ctl,ssr-local三个客户端。我这边实验下来，如果你手机上预编译版本的stairspeedtest并不能正常获取订阅链接的话，v2ray,v2ctl,ssr-local三个客户端的预编译版本也是不能正常工作的。
至于直接提供订阅内容：termux-chroot ./stairspeedtest /u [file contains subscription data | any vaild link]

**Comment by w311ang** [comment]
https://github.com/termux/termux-app/issues/1138#issuecomment-493976000
