### ISSUE TITLE
太难编译了

### ISSUE THREAD

**Issue by pc10201** [tindy2013/stairspeedtest-reborn#78]
在centos 7上提示缺少各种依赖
对cmake,libcurl版本要求也挺高

能否给一个docker镜像的版本？
另外releases打包的能更新一下吗？上次更新是1月份了

**Comment by tindy2013** [comment]
@pc10201 可在actions中下载最新自动构建版本

**Comment by pc10201** [comment]
这个没有windows的构建吗？

**Comment by walwan** [comment]
没有

**Comment by yaoniming-158** [comment]
windows 用户同求1

**Comment by walwan** [comment]
建议加一下telegram组，里面有。

**Comment by petcat** [comment]
> 在centos 7上提示缺少各种依赖
> 对cmake,libcurl版本要求也挺高
> 
> 能否给一个docker镜像的版本？
> 另外releases打包的能更新一下吗？上次更新是1月份了

你不用centos这种软件老掉牙、万年不更的系统不就得了。 debian 、ubuntu 不够新？
