### ISSUE TITLE
请求添加测速节点选择功能

### ISSUE THREAD

**Issue by cranelee** [tindy2013/stairspeedtest-reborn#90]
几十个节点测下来太费流量费时间，能否添加解析出节点后自己选择测速哪些节点？

**Comment by PYniang** [comment]
@cranelee 建议您自己下载配置文件后删除不测的

**Comment by VegeHime** [comment]
@cranelee 可以用websrerver

**Comment by bios99** [comment]
> @cranelee可以用webserver

这个是正解，很好用。
